### ISSUE TITLE
DatabaseError

### ISSUE THREAD

**Issue by hrshy0629** [secureIT-project/CVEfixes#17]
The data version I used is Cvefixes_v1.0.7.sql, and I noticed that CVEfixed/CVEfixes_v1.0.7/Examples uses CVEfixes.db, but it gives an error when I change the path in CVEfixed/CVEfixes_v1.0.7/Examples. I wonder if there is anything changed in the latest version? Or is the database version wrong? Can you help me? 
`DatabaseError:  Execution failed on sql 'SELECT m.name, m.signature, m.nloc, m.parameters, m.token_count, m.code, m.before_change,  f.programming_language FROM method_change m,  file_change f WHERE f.file_change_id=m.file_change_id AND f.programming_language='C'': no such table: method_change`

**Comment by leonmoonen** [comment]
Apologies for the late reply. It looks like you're trying to use the SQL dump file directly. You will need to turn the SQL dump into a sqlite database first (see also INSTALL.md). An easy wrapper around the command to do this is `sh Code/create_CVEfixes_from_dump.sh`
